### ISSUE TITLE
Binary tool no longer available

### ISSUE THREAD

**Issue by ilpiero** [mrwnwttk/afulnx#4]
Well... not really a problem with this project, but looks like American Megatrends is not or no longer providing  afulnx_64 to download.
I fill an Issue just to point it out.

Bye!!

**Comment by jethrogb** [comment]
Link in the readme still works

**Comment by ilpiero** [comment]
Yes... looks like the website has been updated, it pointed to a different page at the time.
Thanks.

**Comment by derjohn** [comment]
http://domoticx.com/bios-tool-ami-flasher-software/ doesn't work anymore
